version: 2

sources:
  - name: dev #schema
    database: weather_db #database
    tables:
      - name: raw_weather_data #table
        columns:
          - name: id
          - name: city
          - name: temperature
          - name: weather_descriptions
          - name: wind_speed
          - name: time
          - name: inserted_at
          - name: utc_offset
